### ISSUE TITLE
BUG- The website is down

### ISSUE THREAD

**Issue by dnet890** [pruvisto/debirdify#33] opened 2024-02-18 10:51 UTC
Hi
I tried to open https://pruvisto.org/debirdify and it just show blank screen. Is it a bug?

**Comment by pruvisto** [comment] 2024-02-19 10:04
It's not supposed to do that. I will investigate what the problem is.

That said, Debirdify has been defunct for about a year anyway because Twitter disabled my API access for supposed violation of its terms of service, without ever explaining in what way I violated them and without responding to support requests. So the website was mostly empty anyway, apart from a message explaning the situation. So I'm closing this ticket.

**Comment by cooljeanius** [comment] 2024-11-02 05:51
> So I'm closing this ticket.

...it still seems to be open, though?

**Closed** 2024-11-02 13:25 UTC

**Comment by pruvisto** [comment] 2024-11-02 13:26
Won't fix since Debirdify clearly cannot work anymore given the new circumstances at Twitter.
